### ISSUE TITLE
VCS packages are removed from the repo if they fail to build

### ISSUE THREAD

**Issue by rabidpug** [alexheretic/aurto#101]
When updating vcs packages, because the build is triggered by removing and then re-adding the package, if the package fails to build it is then no longer in the repo.

Would it be possible to work around this? EG backup the package tar and fallback to aurto addpkg on failure?

**Comment by alexheretic** [comment]
Yeah I agree this isn't ideal. The remove-add method for forcing update of vcs packages is a bit of a sledgehammer approach. I imagine there is probably a better way to ask aurutils to update the package. If so we could switch to that instead and solve this.

**Comment by rabidpug** [comment]
there is [an example](https://github.com/aurutils/aurutils/blob/master/examples/sync-devel) in the aurutils repo for updating vcs packages which I think just clones the source then runs `aur build` on it

**Comment by alexheretic** [comment]
I've released 0.14.0 which should address this
