### ISSUE TITLE
Allow custom makepkg.conf

### ISSUE THREAD

**Issue by ScoreUnder** [alexheretic/aurto#12]
Aurto currently seems to ignore `makepkg.conf`, meaning it uses `xz` to compress packages even though I have chosen `pixz` as my compressor. It would be nice to allow a custom `makepkg.conf` to enable the use of other compressors, though this would probably need some mechanism for installing that software in the chroot in the first place.

**Comment by alexheretic** [comment]
It does indeed ignore your makepkg.conf as it builds in a chroot. 

_devtools_ uses `/usr/share/devtools/makepkg-x86_64.conf` when setting up the chroot. You can edit this, but it isn't ideal as this config is not backed up so a _devtools_ update will overwrite any changes.

Now we've moved to aurutils v2 I think we may be able to specify the makepkg.conf even for chroot builds, so it's something I've been meaning to investigate. If that's true, I'll add an aurto makepkg.conf file that _is_ set as user-backup so users can modify it.

**Comment by alexheretic** [comment]
I've added this with 529a6f8cde16a4949e1269637935e6f949bfd48d. They'll be a customizable `/etc/aurto/makepkg-chroot.conf` in future versions.

Initially I'll leave it identical to `devtools`'s so this won't introduce a change in behaviour. But later I may consider changing the default to better serve the single/lan systems where aurto is probably used the most.
