### ISSUE TITLE
Allow setting database name in config file

### ISSUE THREAD

**Issue by brunomiguel** [alexheretic/aurto#18]

**Comment by alexheretic** [comment]
I'd lean towards this sort of customisation being something you should use [aurutils](https://github.com/AladW/aurutils) directly for. But maybe I haven't considered your use case properly.

**Comment by brunomiguel** [comment]
Imagine having two droplets for two different repositories: one with scientific tools from aur and the other with some packages for personal use also from aur (one is public and the other is not). Aurto will call both of them aurto. To simplify the management of the repos, aurto could allow changing the default db name.

**Comment by alexheretic** [comment]
I do understand why multiple repos might be a nice way of doing things, but aurto is an opinionated simplified and automated aurutils setup. The more you want to customise how it works the more it makes sense to use aurutils directly.

**Comment by brunomiguel** [comment]
It would only be a way for making a simple customization to the repository, but I do understand your rationale
