### ISSUE TITLE
Improve compression speed with xz

### ISSUE THREAD

**Issue by brunomiguel** [alexheretic/aurto#19]
Could you consider adding --threads=0 to the xz entry in the default makepkg-chroot.conf, so compression speed can be improved?

**Comment by alexheretic** [comment]
It's just set as identical to default arch initially, but it exists so users can customize it in the same way as normal makepkg. Updates won't overwrite changes so change it however you please.

Personally I tend to use `PKGEXT='.pkg.tar.gz'` for local packages and will switch to zst when makepkg supports that.

**Comment by alexheretic** [comment]
I'll close this as it's purposely up to users to tweak this.
