### ISSUE TITLE
Error code 13 PermissionDenied

### ISSUE THREAD

**Issue by mygithubthrowaway** [alexheretic/aurto#20]
Hi, new install on my vps.. 

`Error: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }`

the /var/cache/pacman/aurto directory belongs to my user. how i can debug this?

thanks a lot

**Comment by alexheretic** [comment]
What command / timer is seeing this error? 

To debug
* What file is showing the error? 
* What permissions does it have? 
* What user is currently running?

aurto currently only works for a single user, the user that installed aurto. But I'm not sure if that's the problem here.

**Comment by mygithubthrowaway** [comment]
> What command / timer is seeing this error?
> 
> To debug
> 
>     * What file is showing the error?

i don't know, i just installed and trying to:

aurto add aurto

>     * What permissions does it have?

see previous

>     * What user is currently running?
>
my user, user1 with NOPASSWD option on visudo like my working installation of aurto on a difference vps

i suspect: 
/usr/lib/aurto/trust-check

because 

/usr/lib/aurto/update-aurto

work fine

**Comment by alexheretic** [comment]
Most aurto files ie the bin files should be root, as they are simply executed by the user.

Your user should own
* `/var/cache/pacman/aurto`
* `/etc/aurto/trusted-users`

That user should match what's in the root-only `/usr/lib/aurto/user` file. This user should also be in the wheel group.

**Comment by mygithubthrowaway** [comment]
> That user should match what's in the root-only /usr/lib/aurto/user file.

Perfect, this one do the trick, maybe i've started as root, my mistake 

thanks!
