### ISSUE TITLE
Can't verify public key

### ISSUE THREAD

**Issue by BrianAllred** [alexheretic/aurto#24]
Running `$ aurto add lib32-ncurses5-compat-libs` results in 

```
==> Verifying source file signatures with gpg...
    ncurses-6.1.tar.gz ... FAILED (unknown public key 702353E0F7E48EDB)
==> ERROR: One or more PGP signatures could not be verified!
==> ERROR: Could not download sources.
```

I've tried running 

```
$ sudo pacman-key --recv-keys 702353E0F7E48EDB
$ sudo pacman-key --lsign-key 702353E0F7E48EDB
```

Which worked fine, but I guess it doesn't carry over into the chroot.

**Comment by mgolisch** [comment]
you need to add the public key to your user`s gnupg keyring

**Comment by alexheretic** [comment]
Yep running `gpg --recv-keys 702353E0F7E48EDB` should get the build past that.

**Comment by BrianAllred** [comment]
/facepalm

Fixed it. Thanks guys.
