### ISSUE TITLE
Packager email warnings in aurto status

### ISSUE THREAD

**Issue by Kage-Yami** [alexheretic/aurto#27]
I noticed recently that something (I think makepkg) has started showing this warning for a *lot* of packages:

> WARNING: PACKAGER should have the format 'Example Name \<email@address.invalid\>'

Would it be possible to have this entry excluded as a possible match for the Log Warnings shown by `aurto status`? It would make it easier to see where actual issues may exist.

Perhaps with (assuming I got my `grep`-fu right):
```shell
journalctl -eu update-aurto --since '1 week ago' | grep -Ev 'Skipping all source file integrity|PACKAGER should have the format' | grep -E 'ERROR|WARNING' -A5 -B5
```

**Comment by alexheretic** [comment]
Upstream have addressed this https://patchwork.archlinux.org/patch/1289/

On reddit Allan has said:
> ...a week or two for 5.2.1

I don't mind a temporary workaround, but if upstream release in a week or so we could just wait for that. What do you think?

**Comment by Kage-Yami** [comment]
I think it's fair to wait - didn't realise it had been addressed upstream.

**Comment by alexheretic** [comment]
Cool, we can leave this issue open until upstream releases / reopen your pr if that doesn't happen.

**Comment by alexheretic** [comment]
pacman 5.2.1 is out now, includes `makepkg: do not warn about PACKAGER format if not set`. Please re-open if there's still an issue.
