### ISSUE TITLE
When a package in the repo fails to build on update, no packages are updated

### ISSUE THREAD

**Issue by BrianAllred** [alexheretic/aurto#33]
`mullvad-vpn` currently doesn't build in a clean chroot because it depends on `rpm-tools`, which has an optional dependency on `lmdb` when it should be a hard dependency. This caused all other updated packages in the repo to be held back. 

`aurto remove mullvad-vpn` fixed the issue for now, but it seems like a bug if one failed package keeps other good packages from updating.

**Comment by alexheretic** [comment]
1 package update fail will indeed fail them all. I'd also prefer for the others to continue.

After trust-checking aurto runs `aur sync --no-view --no-confirm --database=aurto --makepkg-conf=/etc/aurto/makepkg-chroot.conf --chroot --upgrades`  and aurutils will fail is any package fails to upgrade.

I haven't looked again in details but iirc it's non-trivial to determine which packages have failed. If we can figure that out we can run with `--ignore=mullvad-vpn` to allow the other packages to update.

**Comment by alexheretic** [comment]
Another tactic is to try single package update calls for each aurto package if the normal update fails.

**Comment by Kage-Yami** [comment]
This is potentially a naive question, but is there any benefit to bundling all the package updates into one call?

**Comment by alexheretic** [comment]
> This is potentially a naive question, but is there any benefit to bundling all the package updates into one call?

Mostly because that's the simplest way to do so using aurutils. I guess it can also avoid repeated install/uninstall of make dependencies in the chroot env.

**Comment by Kage-Yami** [comment]
Ah right - yeah, repeated installs/uninstalls sounds yuck (and re-reading, I see I misunderstood your second comment; thought you meant changing all updates to be one-at-a-time, not just when a failure occurs. Oops).

**Comment by AladW** [comment]
Notice you can use `--continue` to avoid `aur-sync` from calling `aur-fetch` again.

**Comment by alexheretic** [comment]
This should be fixed by 21344728c4e6a65d818e6ebdc727f40408c3a766
