### ISSUE TITLE
Empty default-trusted-users.txt

### ISSUE THREAD

**Issue by alexheretic** [alexheretic/aurto#39]
This can go out of sync. This sticks around after install so if trusted users are removed it could be improperly trusting.

**Comment by Noeljunior** [comment]
Where did you get the actual list? Is it updated regularly? If yes we may pull it before the update pkgs procedure and take it as default list. Then we append the user accept list.

**Comment by alexheretic** [comment]
I manually converted it from the wiki list: https://wiki.archlinux.org/index.php/Trusted_Users + me `alexheretic`. There isn't a way (that I know of) to fetch if a user is trusted or not.

The thing is once you install it it's up to the user to maintain it and trusted users can change. I'd rather avoid any automatic updates to it once installed, so it's probably easiest to just start it with me and nothing else.

It isn't too hard to confirm a maintainer when adding a package after all.

**Comment by alexheretic** [comment]
emptied in [v0.9.9](https://github.com/alexheretic/aurto/releases/tag/v0.9.9)
