### ISSUE TITLE
aurto has been deleted in AUR

### ISSUE THREAD

**Issue by rEnr3n** [alexheretic/aurto#46]
I got this notification from AUR. Why?

> freswa [1] deleted aurto [2].
>
> You will no longer receive notifications about this package.
>
> [1] https://aur.archlinux.org/account/freswa/
> [2] https://aur.archlinux.org/pkgbase/aurto/

**Comment by alexheretic** [comment]
Removed by the TUs due to issues with the install script, I'll try to
restore it asap.

Cheers,
-Alex

**Comment by alexheretic** [comment]
Fixed with `0.10.0` release. As deleted-from-aur packages are automatically removed from the 'aurto' repo users will need to re-add aurto to the 'aurto' repo.

```sh
aurto add aurto
```
