### ISSUE TITLE
Improve aurto add output summarizing

### ISSUE THREAD

**Issue by alexheretic** [alexheretic/aurto#49]
Currently only certain lines are shown and are overwritten to reduce the output compared to normal aurutils.

It can get stuck easily as only shows lines that start with `==>`,` ->`. We should show the latest line always, or maybe just remove the summary totally and print everything.

**Comment by codl** [comment]
Personally I would prefer full output, at least as an option. But, at the very least, showing a spinner that moves for each hidden line would indicate that *something* is still happening.
