### ISSUE TITLE
Can't add aurto if repo isn't in /etc/aurto/pacman-chroot.conf

### ISSUE THREAD

**Issue by schtiehve** [alexheretic/aurto#50]
I had some issues with my aurto Server that I couldn't figure out so I installed from scratch.
When getting to the step `aurto add aurto` it would fail because it couldn't statisfy the dependency "aurutils" from the repos. 
It took me a while to figure out that the pacman config in the chroot is now pulled from /etc/aurto/pacman-chroot.conf. 
After addding the aurto repo to that file (including /etc/pacman.d/aurto wont work since that isn't accessible in the chroot)  adding aurto works as expected. 

Maybe it makes sense to add the aurto repo to the /etc/aurto/pacman-chroot.conf on aurto init.

**Comment by alexheretic** [comment]
Thanks! This should be addressed with [**v0.10.4**](https://github.com/alexheretic/aurto/releases/tag/v0.10.4).
