### ISSUE TITLE
Pacman 6 support - ParallelDownloads option

### ISSUE THREAD

**Issue by matt-h** [alexheretic/aurto#51]
Pacman 6 will be introducting a new `pacman.conf` option for `ParallelDownloads`

Here is the error with `aurto`
```
warning: config /etc/pacman.conf line 40: unknown option 'ParallelDownloads'
/usr/bin/aurto: line 25: 2198725 Segmentation fault      sudo pacsync aurto > /dev/null
```

Even though pacman 6 is just in Alpha currently, I wanted to get this note here so support for the `ParallelDownloads` option can be added before it comes out.

**Comment by matt-h** [comment]
Nevermind... the actual issue is in `pacsync` here. I read the error wrong.

**Comment by alexheretic** [comment]
Yeah I don't think aurto will need any changes to support pacman 6, it'll all be upstream aurutils, pacutils, devtools etc.
