### ISSUE TITLE
Aurto fails whenever adding a package

### ISSUE THREAD

**Issue by rkunschke** [alexheretic/aurto#61]
Aurto fails while trying to start the build. Re-initializing doesn't helped.

~ aurto add aurto
aurto: Checking maintainer trust... ✓
aurto: Running: aur sync --no-view --no-confirm --chroot --database=aurto --makepkg-conf=/etc/aurto/makepkg-chroot.conf --pacman-conf=/etc/aurto/pacman-chroot.conf aurto
 ERROR: '/var/lib/aurbuild/x86_64/root' does not appear to be an Arch chroot. 
bsdtar: Failed to set default locale
==> Using [aurto] repository
  -> aurto: (none) -> 0.10.6-3
  -> aurutils: (none) -> 3.1.2-2
error: --local, --sync, and --cache cannot be used as filters
==> Retrieving package files
Cloning into 'aurutils'...
Cloning into 'aurto'...
Running aur chroot --create --makepkg-conf /etc/aurto/makepkg-chroot.conf --pacman-conf /etc/aurto/pacman-chroot.conf
Running aur chroot --update --makepkg-conf /etc/aurto/makepkg-chroot.conf --pacman-conf /etc/aurto/pacman-chroot.conf
==> ERROR: '/var/lib/aurbuild/x86_64/root' does not appear to be an Arch chroot.
`aur sync --no-view --no-confirm --chroot --database=aurto --makepkg-conf=/etc/aurto/makepkg-chroot.conf --pacman-conf=/etc/aurto/pacman-chroot.conf aurto` failed with exit code 255 ✗

**Comment by alexheretic** [comment]
Looks like an issue with the aurutils chroot setup. Try running directly:

aur sync --no-view --no-confirm --chroot --database=aurto
--makepkg-conf=/etc/aurto/makepkg-chroot.conf --pacman-conf=/etc/aurto/
pacman-chroot.conf

Maybe report upstream (aurutils) the output to get the bottom of why is
failing.

**Comment by rkunschke** [comment]
The problem was related to my machines settings and package versions i think. Sorry for that.

**Comment by alexheretic** [comment]
Glad you sorted it 👍
