### ISSUE TITLE
aurto init says "cat: /usr/lib/aurto/user: No such file or directory"

### ISSUE THREAD

**Issue by Malvineous** [alexheretic/aurto#62]
New to aurto, found my way here by the aurget maintainer recommending it.  I'm following the install instructions and I'm getting stuck at this point:
```
# aurto init
cat: /usr/lib/aurto/user: No such file or directory

# aurto status
cat: /usr/lib/aurto/user: No such file or directory

# ls /usr/lib/aurto/
total 508K
drwxr-xr-x   2 root root 4.0K 2021-07-06 16:09 .
drwxr-xr-x 223 root root 152K 2021-07-06 16:09 ..
-rwxr-xr-x   1 root root  936 2021-07-06 16:08 aur-vercmp-devel
-rwxr-xr-x   1 root root   17 2021-07-06 16:08 default-trusted-users.txt
-rwxr-xr-x   1 root root 3.2K 2021-07-06 16:08 install
-rwxr-xr-x   1 root root 1.9K 2021-07-06 16:08 shared-functions
-rwxr-xr-x   1 root root 1.2K 2021-07-06 16:08 summerize-build
-rwxr-xr-x   1 root root 323K 2021-07-06 16:08 trust-check
-rwxr-xr-x   1 root root 3.7K 2021-07-06 16:08 update-aurto
```
What have I missed?

**Comment by alexheretic** [comment]
That file is created when calling `aurto init`. Are you perhaps running that as root? It should be run via some user that aurto will use for non-root aur calls.

There should be a better error message in this case for sure.

**Comment by Malvineous** [comment]
Ah, that was the issue!  I'm running it on a server and I didn't want it tied to my user account, that was why.  A "don't run as root" message would indeed be helpful!
