### ISSUE TITLE
Can the repo be shared across multiple computers?

### ISSUE THREAD

**Issue by Malvineous** [alexheretic/aurto#63]
I have a bunch of Arch machines on my LAN, all running the same architecture, so it would be great if I could set up a shared aurto/aurutils repo as that means I only need to have one machine maintaining the packages that the other machines can pull from.

I see in `/etc/pacman.d/aurto` it points to `file:///var/cache/pacman/aurto` which isn't shared over my LAN.  Is there a way to configure this location so that I can put it in a path that's shared (e.g. `/mnt/fileserver/`) so that one machine will keep updating it but all the other machines can read from it, by pointing Pacman to that same path?

Also, is it possible to have multiple machines monitoring and upgrading the packages in this single shared location, so that if one machine is down, another will do it?

Thanks!

**Comment by alexheretic** [comment]
Yes you should be able to set up one on one machine and use it as a custom repo via the network for all. I'm sure there are aurutils users that do this.

I would assume only the host machine would actually manage the packages, eg you'd ssh into it to run aurto commands.

**Comment by Malvineous** [comment]
That would be fine.  How do I tell aurto to write the packages to a different path, such as `/mnt/fileserver/` instead of `/var/cache/pacman/aurto/`?

**Comment by alexheretic** [comment]
There's no ability to configure that in aurto. I'd look at symbolic linking
or similar

**Comment by Malvineous** [comment]
Thanks for that, symlinking seems to do the job.
