### ISSUE TITLE
Git repositories are not persistent

### ISSUE THREAD

**Issue by Artefact2** [alexheretic/aurto#65]
After I reboot my machine, aurto has to redownload all the git repositories of my *-git AUR packages. Considering that I have fairly slow internet and some of my packages have large repositories, this is not optimal.

I noticed that the repositories are downloaded in `~/.cache/aurto/`, but I'm not sure why its contents gets deleted. My `~/.cache` is on persistent storage and, to my knowledge, none of my other services are cleaning it up.

**Comment by alexheretic** [comment]
Aurto cleans up the aurutils caches after each update. Perhaps that's a bit too aggressive.

**Comment by alexheretic** [comment]
If I remember correctly there are some cases when the caches could be in a state that causes issues, so it was easier to clear them on each update instead of trying to clear them on error.

However, the latter approach would be better for your needs.
