### ISSUE TITLE
sudo 1.9.8.p1-1 causes segmentation fault

### ISSUE THREAD

**Issue by ButteredCats** [alexheretic/aurto#67]
Hi.
I've found that when trying to add something to aurto a segmentation fault occurs when `sudo --preserve-env=SOURCE_DATE_EPOCH -iu builduser bash -c 'cd /startdir; makepkg "$@"' -bash "$@"` is run in the chroot (I think that's the right term). I chrooted in and found that downgrading to sudo 1.9.7.p2-1 seems to fix this.

**Comment by Kernald** [comment]
Got the same issue:
```
/chrootbuild: line 3:     3 Segmentation fault      (core dumped) sudo --preserve-env=SOURCE_DATE_EPOCH -iu builduser bash -c 'cd /startdir; makepkg "$@"' -bash "$@"
```

**Comment by alexheretic** [comment]
I'm not seeing this myself. I'd ensure _aurutils_ & _devtools_ are at their latest version & maybe try removing the chroot files so they get regenerated `sudo rm -rf /var/lib/aurbuild/`?

If that doesn't help we can ask upstream.

**Comment by ButteredCats** [comment]
devtools appears to be up to date (20210202-3) and aurutils too (3.1.2-2). Unfortunately removing all of `/var/lib/aurbuild/` and rerunning `aurto add gzdoom` produces the same error.

**Comment by alexheretic** [comment]
Presumably using **makepkg** directly works ok?

**Comment by ButteredCats** [comment]
Yeah, I've tried other packages too and the only fail when using aurto. gzdoom was just what I've been trying to add.

**Comment by alexheretic** [comment]
You can report this upstream (https://github.com/AladW/aurutils) `aurto add` prints the `aur sync ...` command it runs which you can report as failing (and you should be able to reproduce the issue just running that command without aurto).

**Comment by alexheretic** [comment]
Use the full command that `aurto add ...` prints, e.g.
```sh
aur sync --no-view --no-confirm --chroot --database=aurto --makepkg-conf=/etc/aurto/makepkg-chroot.conf --pacman-conf=/etc/aurto/pacman-chroot.conf gzdoom
```

Important in this case this is the `--chroot` arg.

**Comment by ButteredCats** [comment]
Ah, my bad. That does cause it again, I'll report it.

**Comment by Kernald** [comment]
`sudo` has been updated to 1.9.8.p2-1 and seems to have fixed it.

**Comment by ButteredCats** [comment]
Yeah that's fixed it for me as well, I'll close this
