### ISSUE TITLE
trust-check http2 error

### ISSUE THREAD

**Issue by G4Zz0L1** [alexheretic/aurto#70]
Hi, the systemd daemon has stopped working for the last 2-3 days now.
I've narrowed the problem to the trust-check rust script, but my knowledge stops there, I'm not that fluent with rust.
If I try to launch manually the trust-check script, it gives the same error.
Can you help me to debug it?
I don't know if it's a general problem or something from my setup.

Example screenshot:
![image](https://user-images.githubusercontent.com/13220636/157947170-fa00b619-51a8-4d4f-8e21-04edc6f3be69.png)
![image](https://user-images.githubusercontent.com/13220636/157947226-21b7bd4c-c6af-4944-82a0-7ebbb6ff187e.png)

**Comment by alexheretic** [comment]
I haven't seen this, nor can I reproduce it. I assume all your system dependencies are up to date & aurto is the latest version?

Are you using `core/curl` package or replacing it with something?

**Comment by alexheretic** [comment]
Can you try checking out this project. 
```
cd trust-check
cargo run -- foo
```
Should work with stdout `foo::not-in-aur`.

If that doesn't work try
```
cargo update
cargo run -- foo
```

If both work for you, you may need to rebuild aurto. 
```
aurto remove aurto
aur sync --no-view --no-confirm --chroot --database=aurto --makepkg-conf=/etc/aurto/makepkg-chroot.conf --pacman-conf=/etc/aurto/pacman-chroot.conf aurto
sudo pacman -Syu aurto
```

**Comment by G4Zz0L1** [comment]
It works with the first cargo run, without the update, on a fresh clone.

![image](https://user-images.githubusercontent.com/13220636/157975117-c7583fd7-5e3d-41eb-a487-0a2a3d0866b2.png)

I had already tried to remove, rebuild and reinstall aurto, without success.
I've done it just now, same commands you suggested, it doesn't work.
Same ouput from the trust-check on /usr/lib

**Comment by alexheretic** [comment]
That's strange, rebuilding the package basically recompiles it, pretty much the same thing as running it.

There are some differences, it's compiled in release mode. Can you try `cargo run --release -- foo`

Rebuilding is done in the aurutils chroot. It may be worth trying building it outside the chroot. Or the same aurutils command but without the `--chroot` arg.

If the `cargo run` works you can always just copy that ./target binary to /usr/lib/aurto/trust-check. 

But I don't understand why the aur pkgbuild wouldn't work when building directly would.

**Comment by G4Zz0L1** [comment]
Same thing in release mode.

![image](https://user-images.githubusercontent.com/13220636/157996918-0de45b70-c6b0-4d7b-99f6-161d7cc19454.png)

I just tried removing and uninstalling the package, rebuilding without chroot and even manually copying the generated file into /usr/lib/aurto, but it does the same thing.

It's strange, I've checked the updated packages about the same time it started failing but there isn't much.

I can't understand why it has begin to fail without apparent reason.

**Comment by alexheretic** [comment]
> EDIT2: if I try with a chunk of packages it works fine. I've 486 packages in the pacman -Slq aurto output. Can they be too much?

Yes I think this must be the issue. I'll try to reproduce tomorrow & handle this better.

**Comment by alexheretic** [comment]
Aurweb GET API has a limitation 4443 bytes uri length which you were hitting. Now there's a also POST API that has no such limits, so I've switch to that in v0.12.

**Comment by G4Zz0L1** [comment]
Thanks for the fast fix, now it works!
