### ISSUE TITLE
sudo still asks for password

### ISSUE THREAD

**Issue by bjo81** [alexheretic/aurto#75]
As I use the wheelgroup for myself, I changed `/etc/sudoers.d/50_aurto_passwordless` to:

```
build ALL=(ALL) NOPASSWD: /usr/bin/arch-nspawn
build ALL=(ALL) NOPASSWD: /usr/bin/pacsync aurto
build ALL=(ALL) NOPASSWD:SETENV: /usr/bin/makechrootpkg
```

But something still want's to use another command then in the config?

```
[1/2] env -C /data/build/.cache/aurutils/sync/aurutils '--' 'aur' 'build' '--...to' '--root' '/var/cache/pacman/aurto' && date --rfc-3339=ns > aurutils.stamp
Running aur chroot --create --update --pacman-conf /etc/aurto/pacman-chroot.conf --makepkg-conf /etc/aurto/makepkg-chroot.conf

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for build: 
```

**Comment by AladW** [comment]
Likely from the `sudo install` call https://github.com/AladW/aurutils/blob/master/lib/aur-chroot#L143

**Comment by Gr3q** [comment]
I have the same problem for a couple of months now. 

I had some time, the file `/etc/sudoers.d/50_aurto_passwordless` is correct, but with the new sudo package changes there is another file...`/etc/sudoers.d/99-sudo-group` with the contents of:

```
%sudo ALL=(ALL:ALL) ALL 
```

This seems to make sudo ignore all configs regarding %wheel.

This is my id is someone smarter than me can tell why is this happening.
`uid=1000(gr3q) gid=1000(gr3q) groups=1000(gr3q),962(autologin),974(docker),994(disk),998(wheel),1001(sudo)`
