### ISSUE TITLE
Duplicate packages are created when SigLevel = Optional TrustAll

### ISSUE THREAD

**Issue by rEnr3n** [alexheretic/aurto#78]
I don't want packages being copied to the main CacheDir so I added the aurto dir:
```
CacheDir = /var/cache/pacman/pkg/
CacheDir = /var/cache/pacman/aurto/
```

This does not work as expected. Installing a package built using aurto makes a copy of the package to the first one. Now there are two copies of the same package. When I edit `/etc/pacman.d/aurto` and set `SigLevel = Never`, everything works as expected.

Here's an excerpt from `man aur`:
> In  addition, SigLevel should be set to Never or Always, if package signing is disabled or enabled, respectively. This avoids pacman copying over packages to the main CacheDir, if signature files are missing and SigLevel = Optional is set. (FS#71109)

Is there a reason for using `SigLevel = Optional TrustAll`?

**Comment by alexheretic** [comment]
I think the siglevel had been that since the beginning. It sounds like `Never` could work just as well as the default.

I'll try it out when i get a chance.
