### ISSUE TITLE
aurto can't find libc++ package in AUR

### ISSUE THREAD

**Issue by SeTSeR** [alexheretic/aurto#8]
I'm trying to add Discord to aurto repo and get the following output:
![image](https://user-images.githubusercontent.com/12733495/43045107-1fd299d2-8dbb-11e8-846e-a4491a45c910.png)
But aursearch shows, that these packages are present in AUR:
![image](https://user-images.githubusercontent.com/12733495/43045116-404c1512-8dbb-11e8-860a-cd9cf352959b.png)

**Comment by alexheretic** [comment]
This issue should be fixed in 0.7.4

You can run `aurto add aurto` to keep it updated

**Comment by SeTSeR** [comment]
Thanks, updating solved this problem
