### ISSUE TITLE
Clarification, does aurto also update main repo package when updating AUR packages

### ISSUE THREAD

**Issue by 6XGate** [alexheretic/aurto#90]
So far aurto is proving to be pretty great, but I'm curious if this aurto will update dependent packages from the main Arch repos before updating the AUR packages. I also think this should be clarified in the documents are they contain some recommendations for automatic that if necessary.

**Comment by alexheretic** [comment]
Yep that's how aurutils works. All packages are updated to the latest before each aur build.

**Comment by 6XGate** [comment]
Awesome. Good to know.
