### ISSUE TITLE
Can't remove package

### ISSUE THREAD

**Issue by BrianAllred** [alexheretic/aurto#94]
![image](https://github.com/alexheretic/aurto/assets/5847511/80ac461d-6ec9-4ec3-9690-9b68969ed7b5)

![image](https://github.com/alexheretic/aurto/assets/5847511/3817bf9e-b473-40cd-bdea-bf7162f200c4)

**Comment by BrianAllred** [comment]
Fixed by running `repo-remove ./aurto.db.tar.gz aurutils` and then `aurto add aurutils`. No idea how it got in that state.

**Comment by alexheretic** [comment]
`aurto remove $pkg` runs `repo-remove /var/cache/pacman/aurto/aurto.db.tar "$pkg"`

If it fails it'll print "not found".

What output do you get if you run `repo-remove /var/cache/pacman/aurto/aurto.db.tar aurutils`?

**Comment by alexheretic** [comment]
Ah I think I see the issue, aurto uses `aurto.db.tar` and you have `aurto.db.tar.gz`. Aurto should use the symlink `aurto.db` instead, which I assume you have.

Previously `aurto init` would create  `aurto.db.tar` so perhaps you have .gz because you manually interacted with it?

**Comment by BrianAllred** [comment]
Yes, I was messing around with `repo-add` trying to get a repo database to appear, so it seems I didn't have the correct symlinks. Your solution from #95 fixes this issue. Thanks!
