### ISSUE TITLE
aurto doesn't create db on init

### ISSUE THREAD

**Issue by BrianAllred** [alexheretic/aurto#95]
Run `aurto init` and then `ll /var/cache/pacman/aurto`, there is no repo DB file. This causes all subsequent aurto commands to fail.

**Comment by alexheretic** [comment]
I can reproduce. `aurto init` calls `repo-add /var/cache/pacman/aurto/aurto.db.tar` and this no longer seems to create it :thinking:

**Comment by alexheretic** [comment]
Looks like we can switch to manually creating it with (instead of repo-add)
```
tar acf /var/cache/pacman/aurto/aurto.db.tar.zst -T /dev/null
ln -rs /var/cache/pacman/aurto/aurto.db{.tar.zst,}
```

**Comment by BrianAllred** [comment]
Worked perfectly, thank you!
