### ISSUE TITLE
Selecting a specific dependency?

### ISSUE THREAD

**Issue by BrianAllred** [alexheretic/aurto#97]
I know the point of aurto is to be completely automated with no user input, however, there are certain packages that declare a dependency that can be resolved by multiple different packages.

For example, `tuxguitar` depends on `jack`. Unfortunately, `jack` **the package** is in a bad state in the AUR right now (or rather, one of its dependencies is), but `jack2` in the official repos fulfills the `jack` dependency just fine. However, aurto defaults to the `jack` package and fails to build.

**Comment by AladW** [comment]
This is a devtools issues, because it hardcodes `pacman --noconfirm` in `makechrootpkg`. All you can do is preinstall `jack2` into the chroot with `arch-nspawn`

**Comment by BrianAllred** [comment]
Worked great, thanks!
